import { Agent, AgentRun } from "@/types";

export const MOCK_AGENTS: Agent[] = [
  {
    id: "agent_001",
    userId: "user_001",
    name: "Research Assistant",
    description:
      "Analyzes research papers and provides summaries with cryptographic proof",
    systemPrompt:
      "You are a research assistant specialized in AI and blockchain technology. Provide accurate, well-sourced analysis with clear reasoning chains.",
    model: "gpt-5",
    triggerType: "manual",
    memoryEnabled: true,
    agentId: "mem_agent_001",
    status: "active",
    avatar: "🔬",
    color: "#6366F1",
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
    totalRuns: 47,
    lastRunAt: new Date(Date.now() - 1800000).toISOString(),
    lastRunStatus: "completed",
  },
  {
    id: "agent_002",
    userId: "user_001",
    name: "Code Reviewer",
    description: "Reviews code for security vulnerabilities and best practices",
    systemPrompt:
      "You are an expert code reviewer. Analyze code for security issues, performance problems, and adherence to best practices. Provide actionable feedback.",
    model: "claude-sonnet-4-6",
    triggerType: "webhook",
    memoryEnabled: true,
    agentId: "mem_agent_002",
    status: "active",
    avatar: "💻",
    color: "#10B981",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
    totalRuns: 23,
    lastRunAt: new Date(Date.now() - 3600000).toISOString(),
    lastRunStatus: "completed",
  },
  {
    id: "agent_003",
    userId: "user_001",
    name: "Data Analyst",
    description: "Processes and interprets data with verifiable reasoning",
    systemPrompt:
      "You are a data analyst. Interpret data, identify patterns, and provide insights. Always explain your methodology clearly.",
    model: "grok-4",
    triggerType: "scheduled",
    triggerConfig: { cron: "0 9 * * 1-5" },
    memoryEnabled: false,
    agentId: "mem_agent_003",
    status: "paused",
    avatar: "📊",
    color: "#F59E0B",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    totalRuns: 8,
    lastRunAt: new Date(Date.now() - 86400000).toISOString(),
    lastRunStatus: "failed",
  },
];

export const MOCK_RUNS: AgentRun[] = [
  {
    id: "run_001",
    agentId: "agent_001",
    agentName: "Research Assistant",
    userId: "user_001",
    status: "completed",
    input: "Summarize recent advances in zero-knowledge proofs for AI verification",
    output:
      "Recent advances in ZKML (Zero-Knowledge Machine Learning) have demonstrated promising results for verifiable AI.",
    steps: [],
    proofHash:
      "0x7f9a3c1e8b2d4f6a0e5c9b3d7f1a4e8c2b6d0f3a7e9c1b5d8f2a6e0c4b7d9f1a",
    tokenCount: 847,
    durationMs: 3935,
    startedAt: new Date(Date.now() - 1800000 - 3935).toISOString(),
    completedAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "run_002",
    agentId: "agent_002",
    agentName: "Code Reviewer",
    userId: "user_001",
    status: "completed",
    input: "Review this Solidity smart contract for vulnerabilities",
    output:
      "Security Review Complete. Found 2 potential issues and recommendations.",
    steps: [],
    proofHash:
      "0x3a8f2c1b9e5d7f4a0c8b6d3e1f9a2c5b8d0e4f7a1c3b6d9e2f0a5c7b4d8e1f3",
    tokenCount: 623,
    durationMs: 2840,
    startedAt: new Date(Date.now() - 3600000).toISOString(),
    completedAt: new Date(Date.now() - 3600000 + 2840).toISOString(),
  },
  {
    id: "run_003",
    agentId: "agent_003",
    agentName: "Data Analyst",
    userId: "user_001",
    status: "failed",
    input: "Analyze Q4 trading volume trends",
    steps: [],
    tokenCount: 0,
    durationMs: 450,
    startedAt: new Date(Date.now() - 86400000).toISOString(),
    completedAt: new Date(Date.now() - 86400000 + 450).toISOString(),
  },
];
